// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsoq1PTtne3KRZVxT4v2kjqi5P8-bwcQY',
    appId: '1:615907448347:web:143ef33434b2a3df048abe',
    messagingSenderId: '615907448347',
    projectId: 'appflutter-975c6',
    authDomain: 'appflutter-975c6.firebaseapp.com',
    storageBucket: 'appflutter-975c6.appspot.com',
    measurementId: 'G-E557LTJ7EZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbwBGi97oyzbnayFSZ2WDngA8ththjTFE',
    appId: '1:615907448347:android:1e34e2d27745f4c4048abe',
    messagingSenderId: '615907448347',
    projectId: 'appflutter-975c6',
    storageBucket: 'appflutter-975c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxb2dYWDAtOiRpZwa7wHW1_2qwO904X5k',
    appId: '1:615907448347:ios:30fc8fa152e37b35048abe',
    messagingSenderId: '615907448347',
    projectId: 'appflutter-975c6',
    storageBucket: 'appflutter-975c6.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxb2dYWDAtOiRpZwa7wHW1_2qwO904X5k',
    appId: '1:615907448347:ios:30fc8fa152e37b35048abe',
    messagingSenderId: '615907448347',
    projectId: 'appflutter-975c6',
    storageBucket: 'appflutter-975c6.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsoq1PTtne3KRZVxT4v2kjqi5P8-bwcQY',
    appId: '1:615907448347:web:56d50c7167e2b6a6048abe',
    messagingSenderId: '615907448347',
    projectId: 'appflutter-975c6',
    authDomain: 'appflutter-975c6.firebaseapp.com',
    storageBucket: 'appflutter-975c6.appspot.com',
    measurementId: 'G-5Q2KD29JC3',
  );

}